2024-12-03 20:38:07,746 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\HONOR\proekt\modul_11\modul_12\tests_12_4.py", line 22, in test_run
    name_1 = Runner(15)
             ^^^^^^^^^^
  File "C:\Users\HONOR\proekt\modul_11\modul_12\modul_12_4.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-03 20:38:07,748 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\HONOR\proekt\modul_11\modul_12\tests_12_4.py", line 12, in test_walk
    name = Runner('Кристина', -5)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HONOR\proekt\modul_11\modul_12\modul_12_4.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
